# Generated by Django 3.2.5 on 2021-07-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
